version: '3.0'

services:
  grafana:
    container_name: 'satorici-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.0.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/satorici-datasource
      - ./provisioning:/etc/grafana/provisioning
